name: Build APK Package
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create Zip Package
        run: |
          mkdir -p build
          cp index.html build/
          cd build && zip -r ../PassShieldApp.zip *

      - name: Upload App Package
        uses: actions/upload-artifact@v3
        with:
          name: PassShield-Web-APK-Package
          path: PassShieldApp.zip
